# Generated by Django 4.0.5 on 2022-06-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.IntegerField()),
                ('type', models.TextField()),
                ('name', models.TextField()),
                ('faculty', models.TextField()),
                ('department', models.TextField()),
                ('point_type', models.TextField()),
                ('quota', models.IntegerField()),
                ('accepted', models.IntegerField()),
                ('min_point', models.IntegerField()),
                ('max_point', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Un',
        ),
    ]
