# Generated by Django 4.0.5 on 2022-06-19 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_uni_delete_un'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uni',
            name='department',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='uni',
            name='faculty',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='uni',
            name='max_point',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='uni',
            name='min_point',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='uni',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='uni',
            name='point_type',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='uni',
            name='type',
            field=models.CharField(max_length=30),
        ),
    ]
